# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('lesson_type', models.CharField(choices=[('lecture', "Ma'ruza"), ('practice', 'Amaliy'), ('lab', 'Laboratoriya'), ('seminar', 'Seminar'), ('independent', "Mustaqil ta'lim"), ('exam', 'Imtihon'), ('consultation', 'Konsultatsiya')], max_length=30, verbose_name='Dars turi')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('is_online', models.BooleanField(default=False, verbose_name='Onlaynmi')),
                ('online_url', models.URLField(blank=True, verbose_name='Onlayn dars havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('auditorium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='structure.auditorium', verbose_name='Auditoriya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='structure.organization', verbose_name='Muassasa')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.subjectgroup', verbose_name='Fan-guruh')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('date', models.DateField(db_index=True, verbose_name='Dars sanasi')),
                ('lesson_type', models.CharField(choices=[('lecture', "Ma'ruza"), ('practice', 'Amaliy'), ('lab', 'Laboratoriya'), ('seminar', 'Seminar'), ('independent', "Mustaqil ta'lim"), ('exam', 'Imtihon'), ('consultation', 'Konsultatsiya')], max_length=30, verbose_name='Dars turi')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('is_completed', models.BooleanField(default=False, verbose_name="Dars o'tildimi")),
                ('teacher_comment', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='academics.subjectgroup', verbose_name='Fan-guruh')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_sessions', to='academics.topic', verbose_name='Mavzu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='journal.schedule', verbose_name='Jadval')),
            ],
            options={
                'verbose_name': "Dars mashg'uloti",
                'verbose_name_plural': "Dars mashg'ulotlari",
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kechikdi'), ('excused', 'Sababli'), ('online', 'Masofadan qatnashdi')], max_length=30, verbose_name='Davomad holati')),
                ('late_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Kechikish daqiqasi')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab/izoh')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Belgilangan vaqt')),
                ('changed_reason', models.TextField(blank=True, verbose_name='Tahrir sababi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Belgilagan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.studentprofile', verbose_name='Talaba')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('lesson_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='journal.lessonsession', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Davomad',
                'verbose_name_plural': 'Davomad',
                'indexes': [models.Index(fields=['student', 'status'], name='journal_att_student_149bda_idx'), models.Index(fields=['lesson_session', 'status'], name='journal_att_lesson__701f64_idx')],
                'unique_together': {('lesson_session', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['organization', 'weekday'], name='journal_sch_organiz_5f28ce_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['teacher', 'weekday'], name='journal_sch_teacher_30a5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['auditorium', 'weekday'], name='journal_sch_auditor_4d6976_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='schedule_end_date_after_start'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['date', 'is_completed'], name='journal_les_date_db09f3_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['subject_group', 'date'], name='journal_les_subject_3ea8ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonsession',
            unique_together={('subject_group', 'date', 'lesson_type', 'teacher')},
        ),
    ]
