# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('journal', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=150, verbose_name='Nazorat turi')),
                ('code', models.CharField(max_length=50, verbose_name='Kod')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maksimal ball')),
                ('weight_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Ulush foizi')),
                ('is_final', models.BooleanField(default=False, verbose_name='Yakuniy nazoratmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='structure.organization', verbose_name='Muassasa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Baholash turi',
                'verbose_name_plural': 'Baholash turlari',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ball')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maksimal ball')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan"), ('changed', "O'zgartirilgan"), ('cancelled', 'Bekor qilingan')], default='published', max_length=30, verbose_name='Status')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='Baholangan vaqt')),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='assessment.assessmenttype', verbose_name='Nazorat turi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_grades', to=settings.AUTH_USER_MODEL, verbose_name='Baholagan')),
                ('lesson_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='journal.lessonsession', verbose_name='Dars')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.studentprofile', verbose_name='Talaba')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.subjectgroup', verbose_name='Fan-guruh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('reason', models.TextField(verbose_name='Apellyatsiya sababi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('need_info', "Qo'shimcha ma'lumot kerak"), ('assigned', "Mas'ulga yuborildi"), ('resolved', 'Hal qilindi'), ('rejected', 'Rad etildi'), ('closed', 'Yopildi')], default='new', max_length=30, verbose_name='Status')),
                ('response', models.TextField(blank=True, verbose_name='Javob')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='accounts.studentprofile', verbose_name='Talaba')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='assessment.grade', verbose_name='Baho')),
            ],
            options={
                'verbose_name': 'Apellyatsiya',
                'verbose_name_plural': 'Apellyatsiyalar',
            },
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Eski ball')),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Yangi ball')),
                ('reason', models.TextField(verbose_name="O'zgarish sababi")),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan vaqt")),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_changes', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assessment.grade', verbose_name='Baho')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': "Baho o'zgarish tarixi",
                'verbose_name_plural': "Baho o'zgarish tarixi",
            },
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'subject_group'], name='assessment__student_2f70b8_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject_group', 'assessment_type'], name='assessment__subject_571c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['graded_at'], name='assessment__graded__8ce499_idx'),
        ),
    ]
