# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('scope_type', models.CharField(choices=[('organization', 'Muassasa'), ('faculty', 'Fakultet'), ('department', 'Kafedra'), ('group', 'Guruh'), ('subject', 'Fan'), ('teacher', "O'qituvchi"), ('student', 'Talaba')], max_length=30, verbose_name='Kesim turi')),
                ('scope_id', models.UUIDField(blank=True, null=True, verbose_name='Kesim ID')),
                ('period_start', models.DateField(verbose_name='Davr boshi')),
                ('period_end', models.DateField(verbose_name='Davr oxiri')),
                ('attendance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Davomad foizi')),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name="O'rtacha ball")),
                ('debt_count', models.PositiveIntegerField(default=0, verbose_name='Akademik qarzdorlik soni')),
                ('content_completion_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name="Kontent to'liqligi")),
                ('teacher_activity_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name="O'qituvchi faolligi")),
                ('quality_index', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Sifat indeksi')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ko'rsatkichlar")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='structure.organization', verbose_name='Muassasa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'KPI snapshot',
                'verbose_name_plural': 'KPI snapshotlar',
                'indexes': [models.Index(fields=['organization', 'scope_type'], name='analytics_k_organiz_098b77_idx'), models.Index(fields=['period_start', 'period_end'], name='analytics_k_period__86ad1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='Ogohlantirish')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('risk_level', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Kritik')], max_length=20, verbose_name='Xavf darajasi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal etildimi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='structure.organization', verbose_name='Muassasa')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Hal qilgan')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='accounts.studentprofile', verbose_name='Talaba')),
                ('subject_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='academics.subjectgroup', verbose_name='Fan-guruh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Risk ogohlantirishi',
                'verbose_name_plural': 'Risk ogohlantirishlari',
                'indexes': [models.Index(fields=['organization', 'risk_level', 'is_resolved'], name='analytics_r_organiz_3f9e86_idx')],
            },
        ),
    ]
