# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('employee_id', models.CharField(blank=True, max_length=80, verbose_name='Xodim ID')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Lavozim')),
                ('academic_degree', models.CharField(blank=True, max_length=150, verbose_name='Ilmiy daraja')),
                ('academic_title', models.CharField(blank=True, max_length=150, verbose_name='Ilmiy unvon')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ishga qabul qilingan sana')),
                ('is_teacher', models.BooleanField(default=False, verbose_name="O'qituvchimi")),
            ],
            options={
                'verbose_name': 'Xodim profili',
                'verbose_name_plural': 'Xodim profillari',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Modul kodi')),
                ('name', models.CharField(max_length=150, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', "Ko'rish"), ('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('approve', 'Tasdiqlash'), ('export', 'Eksport'), ('import', 'Import'), ('audit', 'Audit'), ('manage', 'Boshqarish')], max_length=30, verbose_name='Amal')),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='Ruxsat kodi')),
                ('name', models.CharField(max_length=150, verbose_name='Ruxsat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Ruxsat',
                'verbose_name_plural': 'Ruxsatlar',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=150, verbose_name='Rol nomi')),
                ('code', models.CharField(max_length=80, verbose_name='Rol kodi')),
                ('role_type', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('rector', 'Rektor'), ('prorector', 'Prorektor'), ('dean', 'Dekan'), ('department_head', 'Kafedra mudiri'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('quality_control', "Ta'lim sifati nazorati"), ('custom', 'Maxsus rol')], default='custom', max_length=50, verbose_name='Rol turi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_system', models.BooleanField(default=False, verbose_name='Tizim rolimi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha shartlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Rol ruxsati',
                'verbose_name_plural': 'Rol ruxsatlari',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('student_id', models.CharField(max_length=80, verbose_name='Talaba ID')),
                ('education_form', models.CharField(max_length=30, verbose_name="Ta'lim shakli")),
                ('education_level', models.CharField(max_length=30, verbose_name="Ta'lim bosqichi")),
                ('course', models.PositiveSmallIntegerField(verbose_name='Kurs')),
                ('admission_year', models.PositiveSmallIntegerField(verbose_name='Qabul yili')),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='GPA')),
            ],
            options={
                'verbose_name': 'Talaba profili',
                'verbose_name_plural': 'Talaba profillari',
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi roli',
                'verbose_name_plural': 'Foydalanuvchi rollari',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Otasining ismi')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Telefon')),
                ('passport_pinfl', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='JSHSHIR/PINFL')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol'), ('other', 'Boshqa')], max_length=20, verbose_name='Jinsi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/%Y/%m/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('blocked', 'Bloklangan'), ('archived', 'Arxivlangan')], db_index=True, default='active', max_length=20, verbose_name='Holat')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA yoqilganmi')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name="Parol oxirgi o'zgartirilgan vaqt")),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Muvaffaqiyatsiz login urinishlari')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
