# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('document_type', models.CharField(choices=[('order', 'Buyruq'), ('act', 'Dalolatnoma'), ('reference', "Ma'lumotnoma"), ('letter', 'Xizmat xati'), ('task', 'Topshiriq'), ('other', 'Boshqa')], max_length=30, verbose_name='Hujjat turi')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Hujjat raqami')),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('body', models.TextField(blank=True, verbose_name='Hujjat matni')),
                ('file', models.FileField(blank=True, null=True, upload_to='official_documents/%Y/%m/', verbose_name='Hujjat fayli')),
                ('status', models.CharField(choices=[('draft', 'Loyiha'), ('agreement', 'Kelishuvda'), ('approval', 'Tasdiqlashda'), ('approved', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=30, verbose_name='Status')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Imzolangan vaqt')),
                ('e_signature_id', models.CharField(blank=True, max_length=255, verbose_name='ERI identifikatori')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_documents', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='structure.organization', verbose_name='Muassasa')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Imzolagan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Rasmiy hujjat',
                'verbose_name_plural': 'Rasmiy hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tasdiqlash tartibi')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('returned', 'Qaytarildi')], default='waiting', max_length=30, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal bajarilgan vaqt')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.officialdocument', verbose_name='Hujjat')),
            ],
            options={
                'verbose_name': 'Hujjat tasdiqlovi',
                'verbose_name_plural': 'Hujjat tasdiqlovlari',
            },
        ),
        migrations.AddIndex(
            model_name='officialdocument',
            index=models.Index(fields=['organization', 'document_type', 'status'], name='documents_o_organiz_d8c9e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentapproval',
            unique_together={('document', 'approver', 'order')},
        ),
    ]
