# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name="E'lon sarlavhasi")),
                ('body', models.TextField(verbose_name="E'lon matni")),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="E'lon qilish vaqti")),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('is_pinned', models.BooleanField(default=False, verbose_name="Muhim e'lonmi")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.department', verbose_name='Kafedra')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.faculty', verbose_name='Fakultet')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.group', verbose_name='Guruh')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='structure.organization', verbose_name='Muassasa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Mavzu')),
                ('body', models.TextField(verbose_name='Xabar matni')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ichki xabar',
                'verbose_name_plural': 'Ichki xabarlar',
                'indexes': [models.Index(fields=['receiver', 'read_at'], name='communicati_receive_011158_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('request_type', models.CharField(choices=[('technical', 'Texnik muammo'), ('academic', "O'quv jarayoni"), ('appeal', 'Apellyatsiya'), ('document', 'Hujjat'), ('other', 'Boshqa')], max_length=30, verbose_name='Murojaat turi')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('body', models.TextField(verbose_name='Murojaat matni')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('need_info', "Qo'shimcha ma'lumot kerak"), ('assigned', "Mas'ulga yuborildi"), ('resolved', 'Hal qilindi'), ('rejected', 'Rad etildi'), ('closed', 'Yopildi')], default='new', max_length=30, verbose_name='Status')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Ijro muddati')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt')),
                ('response', models.TextField(blank=True, verbose_name='Javob')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='structure.organization', verbose_name='Muassasa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'indexes': [models.Index(fields=['organization', 'status'], name='communicati_organiz_b8175c_idx'), models.Index(fields=['author', 'status'], name='communicati_author__572a8a_idx')],
            },
        ),
    ]
