# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('report_type', models.CharField(max_length=100, verbose_name='Hisobot turi')),
                ('file_format', models.CharField(max_length=20, verbose_name='Fayl formati')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtrlar')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Qatorlar soni')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to='structure.organization', verbose_name='Muassasa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Eksport logi',
                'verbose_name_plural': 'Eksport loglari',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('role_code', models.CharField(blank=True, max_length=80, verbose_name='Rol kodi')),
                ('action', models.CharField(max_length=120, verbose_name='Amal')),
                ('module', models.CharField(blank=True, max_length=120, verbose_name='Modul')),
                ('object_type', models.CharField(blank=True, max_length=120, verbose_name='Obyekt turi')),
                ('object_id', models.CharField(blank=True, max_length=120, verbose_name='Obyekt ID')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Eski qiymatlar')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Yangi qiymatlar')),
                ('result', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('denied', 'Rad etildi')], default='success', max_length=30, verbose_name='Natija')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='Qurilma/Brauzer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='structure.organization', verbose_name='Muassasa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='audit_audit_organiz_01c53f_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['module', 'action'], name='audit_audit_module_365bd8_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Login')),
                ('is_success', models.BooleanField(default=False, verbose_name='Muvaffaqiyatlimi')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='Xatolik sababi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='Qurilma/Brauzer')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Davlat')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='Login vaqti')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.organization', verbose_name='Muassasa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Login tarixi',
                'verbose_name_plural': 'Login tarixi',
                'indexes': [models.Index(fields=['user', 'logged_at'], name='audit_login_user_id_0e13e9_idx'), models.Index(fields=['ip_address', 'logged_at'], name='audit_login_ip_addr_74c4a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('event_type', models.CharField(choices=[('brute_force', 'Brute-force'), ('suspicious_login', 'Shubhali login'), ('permission_denied', 'Ruxsat rad etildi'), ('file_blocked', 'Fayl bloklandi'), ('mass_export', 'Ommaviy eksport'), ('role_changed', "Rol o'zgardi"), ('password_changed', "Parol o'zgardi"), ('other', 'Boshqa')], max_length=50, verbose_name='Hodisa turi')),
                ('risk_level', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Kritik')], default='medium', max_length=20, verbose_name='Xavf darajasi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='Qurilma/Brauzer')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal etildimi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='structure.organization', verbose_name='Muassasa')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL, verbose_name='Hal qilgan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xavfsizlik hodisasi',
                'verbose_name_plural': 'Xavfsizlik hodisalari',
                'indexes': [models.Index(fields=['organization', 'event_type', 'risk_level'], name='audit_secur_organiz_c73f31_idx')],
            },
        ),
    ]
