# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('journal', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Sifat balli')),
                ('content_quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Kontent sifati')),
                ('teaching_quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Dars sifati')),
                ('assessment_transparency_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Baholash shaffofligi')),
                ('conclusion', models.TextField(blank=True, verbose_name='Xulosa')),
                ('recommendations', models.TextField(blank=True, verbose_name='Tavsiyalar')),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tekshiruv vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('inspected_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_lessons', to=settings.AUTH_USER_MODEL, verbose_name="Tekshirilgan o'qituvchi")),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi')),
                ('lesson_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='journal.lessonsession', verbose_name='Dars')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='structure.organization', verbose_name='Muassasa')),
                ('subject_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='academics.subjectgroup', verbose_name='Fan-guruh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sifat tekshiruvi',
                'verbose_name_plural': 'Sifat tekshiruvlari',
            },
        ),
        migrations.CreateModel(
            name='Deficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='Kamchilik')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('risk_level', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Kritik')], default='medium', max_length=20, verbose_name='Xavf darajasi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Bartaraf etish muddati')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Bartaraf etildimi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Bartaraf etilgan vaqt')),
                ('resolution_comment', models.TextField(blank=True, verbose_name='Bartaraf etish izohi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deficiencies', to='structure.organization', verbose_name='Muassasa')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_deficiencies', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deficiencies', to='quality.qualityinspection', verbose_name='Tekshiruv')),
            ],
            options={
                'verbose_name': 'Kamchilik',
                'verbose_name_plural': 'Kamchiliklar',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name="So'rovnoma nomi")),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Anonimmi')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='structure.organization', verbose_name='Muassasa')),
                ('target_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.faculty', verbose_name='Fakultet')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.group', verbose_name='Guruh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('text', models.TextField(verbose_name='Savol')),
                ('question_type', models.CharField(choices=[('rating', 'Reyting'), ('text', 'Matn'), ('single', 'Bitta tanlov'), ('multiple', "Ko'p tanlov")], max_length=30, verbose_name='Savol turi')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Variantlar')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quality.survey', verbose_name="So'rovnoma")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': "So'rovnoma savoli",
                'verbose_name_plural': "So'rovnoma savollari",
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('answer', models.JSONField(default=dict, verbose_name='Javob')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quality.surveyquestion', verbose_name='Savol')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Javob beruvchi')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quality.survey', verbose_name="So'rovnoma")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': "So'rovnoma javobi",
                'verbose_name_plural': "So'rovnoma javoblari",
            },
        ),
    ]
