# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('cpu_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='CPU %')),
                ('memory_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='RAM %')),
                ('disk_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Disk %')),
                ('db_status', models.CharField(default='ok', max_length=50, verbose_name='DB holati')),
                ('queue_size', models.PositiveIntegerField(default=0, verbose_name='Navbat uzunligi')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Faol foydalanuvchilar')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Javob vaqti ms')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha")),
            ],
            options={
                'verbose_name': 'Tizim holati logi',
                'verbose_name_plural': 'Tizim holati loglari',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('backup_type', models.CharField(choices=[('full', "To'liq"), ('incremental', 'Inkremental')], max_length=30, verbose_name='Backup turi')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Fayl manzili')),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Hajm MB')),
                ('is_success', models.BooleanField(default=False, verbose_name='Muvaffaqiyatlimi')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik')),
                ('started_at', models.DateTimeField(verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_logs', to='structure.organization', verbose_name='Muassasa')),
            ],
            options={
                'verbose_name': 'Zaxira nusxa logi',
                'verbose_name_plural': 'Zaxira nusxa loglari',
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('integration_type', models.CharField(choices=[('hemis', 'HEMIS'), ('one_id', 'OneID'), ('sms', 'SMS provayder'), ('email', 'Elektron pochta'), ('e_signature', 'Elektron raqamli imzo'), ('antiplagiat', 'Antiplagiat'), ('storage', 'Fayl saqlash'), ('bi', 'BI/Analitika'), ('other', 'Boshqa')], max_length=40, verbose_name='Integratsiya turi')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('base_url', models.URLField(blank=True, verbose_name='Asosiy URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faolmi')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Sozlamalar')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tekshiruv')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='structure.organization', verbose_name='Muassasa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Integratsiya sozlamasi',
                'verbose_name_plural': 'Integratsiya sozlamalari',
                'unique_together': {('organization', 'integration_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('direction', models.CharField(choices=[('in', 'Kirish'), ('out', 'Chiqish')], max_length=20, verbose_name="Yo'nalish")),
                ('endpoint', models.CharField(blank=True, max_length=255, verbose_name='Endpoint')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name="So'rov")),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Javob')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('partial_error', 'Qisman xato'), ('error', 'Xato'), ('retry', 'Qayta yuborildi')], max_length=30, verbose_name='Status')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Davomiylik ms')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.integrationconfig', verbose_name='Integratsiya')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to='structure.organization', verbose_name='Muassasa')),
            ],
            options={
                'verbose_name': 'Integratsiya logi',
                'verbose_name_plural': 'Integratsiya loglari',
                'indexes': [models.Index(fields=['integration', 'status', 'created_at'], name='integration_integra_cec0fe_idx')],
            },
        ),
    ]
