# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=255, verbose_name='Muassasa nomi')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Muassasa kodi')),
                ('tin', models.CharField(blank=True, max_length=20, verbose_name='STIR')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('rector_full_name', models.CharField(blank=True, max_length=255, verbose_name='Rektor F.I.Sh.')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('blocked', 'Bloklangan'), ('archived', 'Arxivlangan')], default='active', max_length=20, verbose_name='Holat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Muassasa',
                'verbose_name_plural': 'Muassasalar',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=255, verbose_name='Fakultet nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Fakultet kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_faculties', to=settings.AUTH_USER_MODEL, verbose_name='Dekan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='structure.organization', verbose_name='Muassasa')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=255, verbose_name='Kafedra nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Kafedra kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Kafedra mudiri')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='structure.faculty', verbose_name='Fakultet')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='structure.organization', verbose_name='Muassasa')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Bino')),
                ('name', models.CharField(max_length=100, verbose_name='Auditoriya')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Sig'im")),
                ('has_projector', models.BooleanField(default=False, verbose_name='Proyektor bormi')),
                ('has_computers', models.BooleanField(default=False, verbose_name='Kompyuterlar bormi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='structure.organization', verbose_name='Muassasa')),
            ],
            options={
                'verbose_name': 'Auditoriya',
                'verbose_name_plural': 'Auditoriyalar',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(help_text='Masalan: 2026/2027', max_length=20, verbose_name="O'quv yili")),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('is_current', models.BooleanField(default=False, verbose_name="Joriy o'quv yilimi")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='structure.organization', verbose_name='Muassasa')),
            ],
            options={
                'verbose_name': "O'quv yili",
                'verbose_name_plural': "O'quv yillari",
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Semestr nomi')),
                ('semester_type', models.CharField(choices=[('fall', 'Kuzgi'), ('spring', 'Bahorgi'), ('summer', 'Yozgi')], max_length=20, verbose_name='Semestr turi')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Semestr raqami')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('is_current', models.BooleanField(default=False, verbose_name='Joriy semestrmi')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='structure.academicyear', verbose_name="O'quv yili")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='structure.organization', verbose_name='Muassasa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Semestr',
                'verbose_name_plural': 'Semestrlar',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('code', models.CharField(max_length=50, verbose_name="Yo'nalish kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('education_level', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistratura'), ('phd', 'Doktorantura'), ('college', 'Kollej/Litsey')], max_length=30, verbose_name="Ta'lim bosqichi")),
                ('education_form', models.CharField(choices=[('full_time', 'Kunduzgi'), ('part_time', 'Sirtqi'), ('evening', 'Kechki'), ('distance', 'Masofaviy'), ('second_specialty', 'Ikkinchi mutaxassislik')], max_length=30, verbose_name="Ta'lim shakli")),
                ('duration_years', models.PositiveSmallIntegerField(default=4, verbose_name="O'qish muddati")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialties', to='structure.department', verbose_name='Kafedra')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='structure.faculty', verbose_name='Fakultet')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='structure.organization', verbose_name='Muassasa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': "Ta'lim yo'nalishi",
                'verbose_name_plural': "Ta'lim yo'nalishlari",
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Kurs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='structure.academicyear', verbose_name="Qabul o'quv yili")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_groups', to=settings.AUTH_USER_MODEL, verbose_name='Tyutor/Kurator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='structure.department', verbose_name='Kafedra')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='structure.faculty', verbose_name='Fakultet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='structure.organization', verbose_name='Muassasa')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='structure.specialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['code'], name='structure_o_code_2e03d3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='structure_o_status_d3e34a_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['organization', 'is_active'], name='structure_f_organiz_18970f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'faculty', 'is_active'], name='structure_d_organiz_72cb90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='auditorium',
            unique_together={('organization', 'building', 'name')},
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academic_year_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['organization', 'is_current'], name='structure_s_organiz_e01be9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['faculty', 'education_level', 'education_form'], name='structure_s_faculty_6b3f8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['faculty', 'course'], name='structure_g_faculty_fef65c_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['specialty', 'course'], name='structure_g_special_edd9ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('organization', 'name')},
        ),
    ]
