# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name="Ko'rilgan vaqt")),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name="Ko'rish davomiyligi")),
            ],
            options={
                'verbose_name': "Kontent ko'rilishi",
                'verbose_name_plural': "Kontent ko'rilishlari",
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('name', models.CharField(max_length=255, verbose_name="O'quv reja nomi")),
                ('code', models.CharField(max_length=80, verbose_name="O'quv reja kodi")),
                ('total_credits', models.PositiveSmallIntegerField(default=0, verbose_name='Jami kredit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': "O'quv reja",
                'verbose_name_plural': "O'quv rejalar",
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('semester_number', models.PositiveSmallIntegerField(verbose_name='Semestr')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiy fanmi')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Maksimal ball')),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5, verbose_name="O'tish balli")),
            ],
            options={
                'verbose_name': "O'quv rejadagi fan",
                'verbose_name_plural': "O'quv rejadagi fanlar",
            },
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='Kontent nomi')),
                ('content_type', models.CharField(choices=[('file', 'Fayl'), ('video', 'Video'), ('link', 'Havola'), ('text', 'Matn'), ('presentation', 'Prezentatsiya'), ('book', 'Adabiyot'), ('other', 'Boshqa')], max_length=30, verbose_name='Kontent turi')),
                ('text', models.TextField(blank=True, verbose_name='Matn')),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_contents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'zip', 'mp4', 'jpg', 'jpeg', 'png'])], verbose_name='Fayl')),
                ('url', models.URLField(blank=True, verbose_name='Havola')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versiya')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('review', 'Tasdiqlashda'), ('returned', 'Qayta ishlashga qaytarildi'), ('approved', 'Tasdiqlandi'), ('active', 'Faol'), ('archived', 'Arxivlangan')], default='draft', max_length=30, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': "O'quv kontenti",
                'verbose_name_plural': "O'quv kontentlari",
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('code', models.CharField(max_length=80, verbose_name='Fan kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, verbose_name='Fan tavsifi')),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Kredit')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='Jami soat')),
                ('lecture_hours', models.PositiveIntegerField(default=0, verbose_name="Ma'ruza soati")),
                ('practice_hours', models.PositiveIntegerField(default=0, verbose_name='Amaliy soat')),
                ('lab_hours', models.PositiveIntegerField(default=0, verbose_name='Laboratoriya soati')),
                ('independent_hours', models.PositiveIntegerField(default=0, verbose_name="Mustaqil ta'lim soati")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Fan-guruh',
                'verbose_name_plural': 'Fan-guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilganmi")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('lesson_type', models.CharField(choices=[('lecture', "Ma'ruza"), ('practice', 'Amaliy'), ('lab', 'Laboratoriya'), ('seminar', 'Seminar'), ('independent', "Mustaqil ta'lim"), ('exam', 'Imtihon'), ('consultation', 'Konsultatsiya')], max_length=30, verbose_name='Dars turi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Rejadagi sana')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('review', 'Tasdiqlashda'), ('returned', 'Qayta ishlashga qaytarildi'), ('approved', 'Tasdiqlandi'), ('active', 'Faol'), ('archived', 'Arxivlangan')], default='draft', max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['subject_group', 'order'],
            },
        ),
    ]
