# Generated by Django 6.0.4 on 2026-05-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='contentview',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='contentview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='contentview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculums', to='structure.academicyear', verbose_name="O'quv yili"),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='structure.organization', verbose_name='Muassasa'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='structure.specialty', verbose_name="Yo'nalish"),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academics.curriculum', verbose_name="O'quv reja"),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contents', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='contentview',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='academics.learningcontent', verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='structure.department', verbose_name="Mas'ul kafedra"),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='structure.organization', verbose_name='Muassasa'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_subjects', to='academics.subject', verbose_name='Fan'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='assistant_teachers',
            field=models.ManyToManyField(blank=True, related_name='assistant_subject_groups', to=settings.AUTH_USER_MODEL, verbose_name="Yordamchi o'qituvchilar"),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_groups', to='structure.group', verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='main_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_subject_groups', to=settings.AUTH_USER_MODEL, verbose_name="Asosiy o'qituvchi"),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='structure.organization', verbose_name='Muassasa'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_groups', to='structure.semester', verbose_name='Semestr'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_groups', to='academics.subject', verbose_name='Fan'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_items', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='topic',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.subjectgroup', verbose_name='Fan-guruh'),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='academics.topic', verbose_name='Mavzu'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['user', 'viewed_at'], name='academics_c_user_id_fe7b2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentview',
            unique_together={('content', 'user')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department', 'is_active'], name='academics_s_departm_2b0179_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together={('curriculum', 'subject', 'semester_number')},
        ),
        migrations.AddIndex(
            model_name='subjectgroup',
            index=models.Index(fields=['organization', 'semester'], name='academics_s_organiz_42a60d_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectgroup',
            index=models.Index(fields=['main_teacher', 'semester'], name='academics_s_main_te_91df29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectgroup',
            unique_together={('subject', 'group', 'semester')},
        ),
        migrations.AddIndex(
            model_name='learningcontent',
            index=models.Index(fields=['topic', 'status'], name='academics_l_topic_i_0e6cea_idx'),
        ),
    ]
